const countries = [
  {
    hun: "Afganisztán",
    eng: "Afghanistan",
    esp: "Afganistán",
    fra: "Afghanistan",
  },
  {
    hun: "Åland-szigetek",
    eng: "Åland Islands",
    esp: "Islas Åland",
    fra: "Îles Åland",
  },
  {
    hun: "Albánia",
    eng: "Albania",
    esp: "Albania",
    fra: "Albanie",
  },
  {
    hun: "Algéria",
    eng: "Algeria",
    esp: "Argelia",
    fra: "Algérie",
  },
  {
    hun: "Amerikai Szamoa",
    eng: "American Samoa",
    esp: "Samoa Americana",
    fra: "Samoa américaines",
  },
  {
    hun: "Andorra",
    eng: "Andorra",
    esp: "Andorra",
    fra: "Andorre",
  },
  {
    hun: "Angola",
    eng: "Angola",
    esp: "Angola",
    fra: "Angola",
  },
  {
    hun: "Anguilla",
    eng: "Anguilla",
    esp: "Anguila",
    fra: "Anguilla",
  },
  {
    hun: "Antarktisz",
    eng: "Antarctica",
    esp: "Antártida",
    fra: "Antarctique",
  },
  {
    hun: "Antigua és Barbuda",
    eng: "Antigua and Barbuda",
    esp: "Antigua y Barbuda",
    fra: "Antigua-et-Barbuda",
  },
  {
    hun: "Argentína",
    eng: "Argentina",
    esp: "Argentina",
    fra: "Argentine",
  },
  {
    hun: "Örményország",
    eng: "Armenia",
    esp: "Armenia",
    fra: "Arménie",
  },
  {
    hun: "Aruba",
    eng: "Aruba",
    esp: "Aruba",
    fra: "Aruba",
  },
  {
    hun: "Ausztrália",
    eng: "Australia",
    esp: "Australia",
    fra: "Australie",
  },
  {
    hun: "Ausztria",
    eng: "Austria",
    esp: "Austria",
    fra: "Autriche",
  },
  {
    hun: "Azerbajdzsán",
    eng: "Azerbaijan",
    esp: "Azerbaiyán",
    fra: "Azerbaïdjan",
  },
  {
    hun: "Bahama-szigetek",
    eng: "Bahamas",
    esp: "Bahamas",
    fra: "Bahamas",
  },
  {
    hun: "Bahrein",
    eng: "Bahrain",
    esp: "Baréin",
    fra: "Bahreïn",
  },
  {
    hun: "Banglades",
    eng: "Bangladesh",
    esp: "Bangladesh",
    fra: "Bangladesh",
  },
  {
    hun: "Barbados",
    eng: "Barbados",
    esp: "Barbados",
    fra: "Barbade",
  },
  {
    hun: "Fehéroroszország",
    eng: "Belarus",
    esp: "Bielorrusia",
    fra: "Biélorussie",
  },
  {
    hun: "Belgium",
    eng: "Belgium",
    esp: "Bélgica",
    fra: "Belgique",
  },
  {
    hun: "Belize",
    eng: "Belize",
    esp: "Belice",
    fra: "Belize",
  },
  {
    hun: "Benin",
    eng: "Benin",
    esp: "Benín",
    fra: "Bénin",
  },
  {
    hun: "Bermuda",
    eng: "Bermuda",
    esp: "Bermudas",
    fra: "Bermudes",
  },
  {
    hun: "Bhután",
    eng: "Bhutan",
    esp: "Bután",
    fra: "Bhoutan",
  },
  {
    hun: "Bolívia",
    eng: "Bolivia",
    esp: "Bolivia",
    fra: "Bolivie",
  },
  {
    hun: "Bosznia-Hercegovina",
    eng: "Bosnia and Herzegovina",
    esp: "Bosnia y Herzegovina",
    fra: "Bosnie-Herzégovine",
  },
  {
    hun: "Botswana",
    eng: "Botswana",
    esp: "Botsuana",
    fra: "Botswana",
  },
  {
    hun: "Bouvet-sziget",
    eng: "Bouvet Island",
    esp: "Isla Bouvet",
    fra: "Île Bouvet",
  },
  {
    hun: "Brazília",
    eng: "Brazil",
    esp: "Brasil",
    fra: "Brésil",
  },
  {
    hun: "Brit Indiai-óceáni Terület",
    eng: "British Indian Ocean Territory",
    esp: "Territorio Británico del Océano Índico",
    fra: "Territoire britannique de l'océan Indien",
  },
  {
    hun: "Brunei",
    eng: "Brunei Darussalam",
    esp: "Brunéi",
    fra: "Brunei",
  },
  {
    hun: "Bulgária",
    eng: "Bulgaria",
    esp: "Bulgaria",
    fra: "Bulgarie",
  },
  {
    hun: "Burkina Faso",
    eng: "Burkina Faso",
    esp: "Burkina Faso",
    fra: "Burkina Faso",
  },
  {
    hun: "Burundi",
    eng: "Burundi",
    esp: "Burundi",
    fra: "Burundi",
  },
  { hun: "Kambodzsa", eng: "Cambodia", esp: "Camboya", fra: "Cambodge" },
  { hun: "Kamerun", eng: "Cameroon", esp: "Camerún", fra: "Cameroun" },
  { hun: "Kanada", eng: "Canada", esp: "Canadá", fra: "Canada" },
  {
    hun: "Zöld-foki Köztársaság",
    eng: "Cape Verde",
    esp: "Cabo Verde",
    fra: "Cap-Vert",
  },
  {
    hun: "Kajmán-szigetek",
    eng: "Cayman Islands",
    esp: "Islas Caimán",
    fra: "Îles Caïmans",
  },
  {
    hun: "Közép-afrikai Köztársaság",
    eng: "Central African Republic",
    esp: "República Centroafricana",
    fra: "République centrafricaine",
  },
  { hun: "Csád", eng: "Chad", esp: "Chad", fra: "Tchad" },
  { hun: "Chile", eng: "Chile", esp: "Chile", fra: "Chili" },
  { hun: "Kína", eng: "China", esp: "China", fra: "Chine" },
  {
    hun: "Karácsony-sziget",
    eng: "Christmas Island",
    esp: "Isla de Navidad",
    fra: "Île Christmas",
  },
  {
    hun: "Kókusz (Keeling)-szigetek",
    eng: "Cocos (Keeling) Islands",
    esp: "Islas Cocos (Keeling)",
    fra: "Îles Cocos (Keeling)",
  },
  { hun: "Kolumbia", eng: "Colombia", esp: "Colombia", fra: "Colombie" },
  { hun: "Comore-szigetek", eng: "Comoros", esp: "Comoras", fra: "Comores" },
  { hun: "Kongó", eng: "Congo", esp: "Congo", fra: "Congo" },
  {
    hun: "Kongói Demokratikus Köztársaság",
    eng: "Congo, The Democratic Republic of the",
    esp: "Congo, República Democrática del",
    fra: "Congo, République démocratique du",
  },
  {
    hun: "Cook-szigetek",
    eng: "Cook Islands",
    esp: "Islas Cook",
    fra: "Îles Cook",
  },
  {
    hun: "Costa Rica",
    eng: "Costa Rica",
    esp: "Costa Rica",
    fra: "Costa Rica",
  },
  {
    hun: "Elefántcsontpart",
    eng: "Cote D'Ivoire",
    esp: "Costa de Marfil",
    fra: "Côte d'Ivoire",
  },
  { hun: "Horvátország", eng: "Croatia", esp: "Croacia", fra: "Croatie" },
  { hun: "Kuba", eng: "Cuba", esp: "Cuba", fra: "Cuba" },
  { hun: "Ciprus", eng: "Cyprus", esp: "Chipre", fra: "Chypre" },
  {
    hun: "Cseh Köztársaság",
    eng: "Czech Republic",
    esp: "República Checa",
    fra: "République tchèque",
  },
  { hun: "Dánia", eng: "Denmark", esp: "Dinamarca", fra: "Danemark" },
  { hun: "Dzsibuti", eng: "Djibouti", esp: "Yibuti", fra: "Djibouti" },
  {
    hun: "Dominika",
    eng: "Dominica",
    esp: "Dominica",
    fra: "Dominique",
  },
  {
    hun: "Dominikai Köztársaság",
    eng: "Dominican Republic",
    esp: "República Dominicana",
    fra: "République dominicaine",
  },
  { hun: "Ecuador", eng: "Ecuador", esp: "Ecuador", fra: "Équateur" },
  { hun: "Egyiptom", eng: "Egypt", esp: "Egipto", fra: "Égypte" },
  {
    hun: "El Salvador",
    eng: "El Salvador",
    esp: "El Salvador",
    fra: "Salvador",
  },
  {
    hun: "Egyenlítői-Guinea",
    eng: "Equatorial Guinea",
    esp: "Guinea Ecuatorial",
    fra: "Guinée équatoriale",
  },
  { hun: "Eritrea", eng: "Eritrea", esp: "Eritrea", fra: "Érythrée" },
  { hun: "Észtország", eng: "Estonia", esp: "Estonia", fra: "Estonie" },
  { hun: "Etiópia", eng: "Ethiopia", esp: "Etiopía", fra: "Éthiopie" },
  {
    hun: "Falkland-szigetek (Malvinas)",
    eng: "Falkland Islands (Malvinas)",
    esp: "Islas Malvinas",
    fra: "Îles Falkland",
  },
  {
    hun: "Faroe-szigetek",
    eng: "Faroe Islands",
    esp: "Islas Feroe",
    fra: "Îles Féroé",
  },
  { hun: "Fidzsi-szigetek", eng: "Fiji", esp: "Fiyi", fra: "Fidji" },
  { hun: "Finnország", eng: "Finland", esp: "Finlandia", fra: "Finlande" },
  { hun: "Franciaország", eng: "France", esp: "Francia", fra: "France" },
  {
    hun: "Francia Guyana",
    eng: "French Guiana",
    esp: "Guayana Francesa",
    fra: "Guyane française",
  },
  {
    hun: "Francia Polinézia",
    eng: "French Polynesia",
    esp: "Polinesia Francesa",
    fra: "Polynésie française",
  },
  {
    hun: "Francia Déli Területek",
    eng: "French Southern Territories",
    esp: "Territorios Franceses del Sur",
    fra: "Terres australes françaises",
  },
  { hun: "Gabon", eng: "Gabon", esp: "Gabón", fra: "Gabon" },
  { hun: "Gambia", eng: "Gambia", esp: "Gambia", fra: "Gambie" },
  { hun: "Grúzia", eng: "Georgia", esp: "Georgia", fra: "Géorgie" },
  { hun: "Németország", eng: "Germany", esp: "Alemania", fra: "Allemagne" },
  { hun: "Ghána", eng: "Ghana", esp: "Ghana", fra: "Ghana" },
  { hun: "Gibraltár", eng: "Gibraltar", esp: "Gibraltar", fra: "Gibraltar" },
  { hun: "Görögország", eng: "Greece", esp: "Grecia", fra: "Grèce" },
  { hun: "Grönland", eng: "Greenland", esp: "Groenlandia", fra: "Groenland" },
  { hun: "Grenada", eng: "Grenada", esp: "Granada", fra: "Grenade" },
  {
    hun: "Guadeloupe",
    eng: "Guadeloupe",
    esp: "Guadalupe",
    fra: "Guadeloupe",
  },
  { hun: "Guam", eng: "Guam", esp: "Guam", fra: "Guam" },
  { hun: "Guatemala", eng: "Guatemala", esp: "Guatemala", fra: "Guatemala" },
  { hun: "Guernsey", eng: "Guernsey", esp: "Guernsey", fra: "Guernesey" },
  { hun: "Guinea", eng: "Guinea", esp: "Guinea", fra: "Guinée" },
  {
    hun: "Guinea-Bissau",
    eng: "Guinea-Bissau",
    esp: "Guinea-Bissau",
    fra: "Guinée-Bissau",
  },
  { hun: "Guyana", eng: "Guyana", esp: "Guyana", fra: "Guyana" },
  { hun: "Haiti", eng: "Haiti", esp: "Haití", fra: "Haïti" },
  {
    hun: "Heard-sziget és McDonald-szigetek",
    eng: "Heard Island and Mcdonald Islands",
    esp: "Islas Heard y McDonald",
    fra: "Îles Heard-et-MacDonald",
  },
  {
    hun: "Szentszék (Vatikán)",
    eng: "Holy See (Vatican City State)",
    esp: "Santa Sede (Ciudad del Vaticano)",
    fra: "Saint-Siège (État de la Cité du Vatican)",
  },
  { hun: "Honduras", eng: "Honduras", esp: "Honduras", fra: "Honduras" },
  { hun: "Hongkong", eng: "Hong Kong", esp: "Hong Kong", fra: "Hong Kong" },
  { hun: "Magyarország", eng: "Hungary", esp: "Hungría", fra: "Hongrie" },
  { hun: "Izland", eng: "Iceland", esp: "Islandia", fra: "Islande" },
  { hun: "India", eng: "India", esp: "India", fra: "Inde" },
  { hun: "Indonézia", eng: "Indonesia", esp: "Indonesia", fra: "Indonésie" },
  {
    hun: "Irán, Iszlám Köztársaság",
    eng: "Iran, Islamic Republic Of",
    esp: "Irán, República Islámica de",
    fra: "Iran, République islamique d'",
  },
  { hun: "Irak", eng: "Iraq", esp: "Irak", fra: "Irak" },
  { hun: "Írország", eng: "Ireland", esp: "Irlanda", fra: "Irlande" },
  {
    hun: "Man-sziget",
    eng: "Isle of Man",
    esp: "Isla de Man",
    fra: "Île de Man",
  },
  { hun: "Izrael", eng: "Israel", esp: "Israel", fra: "Israël" },
  { hun: "Olaszország", eng: "Italy", esp: "Italia", fra: "Italie" },
  { hun: "Jamaica", eng: "Jamaica", esp: "Jamaica", fra: "Jamaïque" },
  { hun: "Japán", eng: "Japan", esp: "Japón", fra: "Japon" },
  { hun: "Jersey", eng: "Jersey", esp: "Jersey", fra: "Jersey" },
  { hun: "Jordánia", eng: "Jordan", esp: "Jordania", fra: "Jordanie" },
  {
    hun: "Kazahsztán",
    eng: "Kazakhstan",
    esp: "Kazajistán",
    fra: "Kazakhstan",
  },
  { hun: "Kenya", eng: "Kenya", esp: "Kenia", fra: "Kenya" },
  { hun: "Kiribati", eng: "Kiribati", esp: "Kiribati", fra: "Kiribati" },
  {
    hun: "Koreai Népi Demokratikus Köztársaság",
    eng: "Korea, Democratic People'S Republic of",
    esp: "República Popular Democrática de Corea",
    fra: "Corée du Nord",
  },
  {
    hun: "Dél-Korea",
    eng: "Korea, Republic of",
    esp: "Corea del Sur",
    fra: "Corée du Sud",
  },
  { hun: "Kuvait", eng: "Kuwait", esp: "Kuwait", fra: "Koweït" },
  {
    hun: "Kirgizisztán",
    eng: "Kyrgyzstan",
    esp: "Kirguistán",
    fra: "Kirghizistan",
  },
  {
    hun: "Laosz",
    eng: "Lao People'S Democratic Republic",
    esp: "Laos, República Democrática Popular",
    fra: "Laos",
  },
  { hun: "Lettország", eng: "Latvia", esp: "Letonia", fra: "Lettonie" },
  { hun: "Libanon", eng: "Lebanon", esp: "Líbano", fra: "Liban" },
  { hun: "Lesotho", eng: "Lesotho", esp: "Lesoto", fra: "Lesotho" },
  { hun: "Libéria", eng: "Liberia", esp: "Liberia", fra: "Libéria" },
  { hun: "Líbia", eng: "Libyan Arab Jamahiriya", esp: "Libia", fra: "Libye" },
  {
    hun: "Liechtenstein",
    eng: "Liechtenstein",
    esp: "Liechtenstein",
    fra: "Liechtenstein",
  },
  { hun: "Litvánia", eng: "Lithuania", esp: "Lituania", fra: "Lituanie" },
  {
    hun: "Luxemburg",
    eng: "Luxembourg",
    esp: "Luxemburgo",
    fra: "Luxembourg",
  },
  { hun: "Macao", eng: "Macao", esp: "Macao", fra: "Macao" },
  {
    hun: "Macedónia, a Volt Jugoszláv Köztársaság",
    eng: "Macedonia, The Former Yugoslav Republic of",
    esp: "Macedonia, la Antigua República Yugoslava de",
    fra: "Macédoine du Nord",
  },
  {
    hun: "Madagaszkár",
    eng: "Madagascar",
    esp: "Madagascar",
    fra: "Madagascar",
  },
  { hun: "Malawi", eng: "Malawi", esp: "Malawi", fra: "Malawi" },
  { hun: "Malajzia", eng: "Malaysia", esp: "Malasia", fra: "Malaisie" },
  {
    hun: "Maldív-szigetek",
    eng: "Maldives",
    esp: "Maldivas",
    fra: "Maldives",
  },
  { hun: "Mali", eng: "Mali", esp: "Mali", fra: "Mali" },
  { hun: "Málta", eng: "Malta", esp: "Malta", fra: "Malte" },
  {
    hun: "Marshall-szigetek",
    eng: "Marshall Islands",
    esp: "Islas Marshall",
    fra: "Îles Marshall",
  },
  {
    hun: "Martinique",
    eng: "Martinique",
    esp: "Martinica",
    fra: "Martinique",
  },
  {
    hun: "Mauritánia",
    eng: "Mauritania",
    esp: "Mauritania",
    fra: "Mauritanie",
  },
  { hun: "Mauritius", eng: "Mauritius", esp: "Mauricio", fra: "Maurice" },
  { hun: "Mayotte", eng: "Mayotte", esp: "Mayotte", fra: "Mayotte" },
  { hun: "Mexikó", eng: "Mexico", esp: "México", fra: "Mexique" },
  {
    hun: "Mikronézia, Szövetségi Államok",
    eng: "Micronesia, Federated States of",
    esp: "Micronesia, Estados Federados de",
    fra: "Micronésie",
  },
  {
    hun: "Moldova, Köztársaság",
    eng: "Moldova, Republic of",
    esp: "Moldova, República de",
    fra: "Moldavie",
  },
  { hun: "Monaco", eng: "Monaco", esp: "Mónaco", fra: "Monaco" },
  { hun: "Mongólia", eng: "Mongolia", esp: "Mongolia", fra: "Mongolie" },
  {
    hun: "Montserrat",
    eng: "Montserrat",
    esp: "Montserrat",
    fra: "Montserrat",
  },
  { hun: "Marokkó", eng: "Morocco", esp: "Marruecos", fra: "Maroc" },
  {
    hun: "Mozambik",
    eng: "Mozambique",
    esp: "Mozambique",
    fra: "Mozambique",
  },
  { hun: "Mianmar", eng: "Myanmar", esp: "Myanmar", fra: "Myanmar" },
  { hun: "Namíbia", eng: "Namibia", esp: "Namibia", fra: "Namibie" },
  { hun: "Nauru", eng: "Nauru", esp: "Nauru", fra: "Nauru" },
  { hun: "Nepál", eng: "Nepal", esp: "Nepal", fra: "Népal" },
  {
    hun: "Hollandia",
    eng: "Netherlands",
    esp: "Países Bajos",
    fra: "Pays-Bas",
  },
  {
    hun: "Holland Antillák",
    eng: "Netherlands Antilles",
    esp: "Antillas Neerlandesas",
    fra: "Antilles néerlandaises",
  },
  {
    hun: "Új-Kaledónia",
    eng: "New Caledonia",
    esp: "Nueva Caledonia",
    fra: "Nouvelle-Calédonie",
  },
  {
    hun: "Új-Zéland",
    eng: "New Zealand",
    esp: "Nueva Zelanda",
    fra: "Nouvelle-Zélande",
  },
  { hun: "Nicaragua", eng: "Nicaragua", esp: "Nicaragua", fra: "Nicaragua" },
  { hun: "Niger", eng: "Niger", esp: "Níger", fra: "Niger" },
  { hun: "Nigéria", eng: "Nigeria", esp: "Nigeria", fra: "Nigéria" },
  { hun: "Niue", eng: "Niue", esp: "Niue", fra: "Niue" },
  {
    hun: "Norfolk-sziget",
    eng: "Norfolk Island",
    esp: "Isla Norfolk",
    fra: "Île Norfolk",
  },
  {
    hun: "Északi-Mariana-szigetek",
    eng: "Northern Mariana Islands",
    esp: "Islas Marianas del Norte",
    fra: "Îles Mariannes du Nord",
  },
  { hun: "Norvégia", eng: "Norway", esp: "Noruega", fra: "Norvège" },
  { hun: "Omán", eng: "Oman", esp: "Omán", fra: "Oman" },
  { hun: "Pakisztán", eng: "Pakistan", esp: "Pakistán", fra: "Pakistan" },
  { hun: "Palau", eng: "Palau", esp: "Palau", fra: "Palaos" },
  {
    hun: "Palesztin Terület, Elfoglalt",
    eng: "Palestinian Territory, Occupied",
    esp: "Territorio Palestino Ocupado",
    fra: "Territoire palestinien occupé",
  },
  { hun: "Panama", eng: "Panama", esp: "Panamá", fra: "Panama" },
  {
    hun: "Pápua Új-Guinea",
    eng: "Papua New Guinea",
    esp: "Papúa Nueva Guinea",
    fra: "Papouasie-Nouvelle-Guinée",
  },
  { hun: "Paraguay", eng: "Paraguay", esp: "Paraguay", fra: "Paraguay" },
  { hun: "Peru", eng: "Peru", esp: "Perú", fra: "Pérou" },
  {
    hun: "Fülöp-szigetek",
    eng: "Philippines",
    esp: "Filipinas",
    fra: "Philippines",
  },
  {
    hun: "Pitcairn-szigetek",
    eng: "Pitcairn",
    esp: "Islas Pitcairn",
    fra: "Îles Pitcairn",
  },
  { hun: "Lengyelország", eng: "Poland", esp: "Polonia", fra: "Pologne" },
  { hun: "Portugália", eng: "Portugal", esp: "Portugal", fra: "Portugal" },
  {
    hun: "Puerto Rico",
    eng: "Puerto Rico",
    esp: "Puerto Rico",
    fra: "Porto Rico",
  },
  { hun: "Katar", eng: "Qatar", esp: "Catar", fra: "Qatar" },
  { hun: "Réunion", eng: "Reunion", esp: "Reunión", fra: "Réunion" },
  { hun: "Románia", eng: "Romania", esp: "Rumania", fra: "Roumanie" },
  {
    hun: "Orosz Föderáció",
    eng: "Russian Federation",
    esp: "Federación Rusa",
    fra: "Fédération de Russie",
  },
  { hun: "Ruanda", eng: "Rwanda", esp: "Ruanda", fra: "Rwanda" },
  {
    hun: "Szent Ilona",
    eng: "Saint Helena",
    esp: "Santa Elena",
    fra: "Sainte-Hélène",
  },
  {
    hun: "Saint Kitts és Nevis",
    eng: "Saint Kitts and Nevis",
    esp: "San Cristóbal y Nieves",
    fra: "Saint-Christophe-et-Niévès",
  },
  {
    hun: "Saint Lucia",
    eng: "Saint Lucia",
    esp: "Santa Lucía",
    fra: "Sainte-Lucie",
  },
  {
    hun: "Saint Pierre és Miquelon",
    eng: "Saint Pierre and Miquelon",
    esp: "San Pedro y Miquelón",
    fra: "Saint-Pierre-et-Miquelon",
  },
  {
    hun: "Saint Vincent és a Grenadine-szigetek",
    eng: "Saint Vincent and the Grenadines",
    esp: "San Vicente y las Granadinas",
    fra: "Saint-Vincent-et-les-Grenadines",
  },
  { hun: "Szamoa", eng: "Samoa", esp: "Samoa", fra: "Samoa" },
  {
    hun: "San Marino",
    eng: "San Marino",
    esp: "San Marino",
    fra: "Saint-Marin",
  },
  {
    hun: "Sao Tomé és Príncipe",
    eng: "Sao Tome and Principe",
    esp: "Santo Tomé y Príncipe",
    fra: "Sao Tomé-et-Principe",
  },
  {
    hun: "Szaúd-Arábia",
    eng: "Saudi Arabia",
    esp: "Arabia Saudita",
    fra: "Arabie Saoudite",
  },
  { hun: "Szenegál", eng: "Senegal", esp: "Senegal", fra: "Sénégal" },
  {
    hun: "Szerbia és Montenegró",
    eng: "Serbia and Montenegro",
    esp: "Serbia y Montenegro",
    fra: "Serbie-et-Monténégro",
  },
  {
    hun: "Seychelle-szigetek",
    eng: "Seychelles",
    esp: "Seychelles",
    fra: "Seychelles",
  },
  {
    hun: "Sierra Leone",
    eng: "Sierra Leone",
    esp: "Sierra Leona",
    fra: "Sierra Leone",
  },
  { hun: "Szingapúr", eng: "Singapore", esp: "Singapur", fra: "Singapour" },
  { hun: "Szlovákia", eng: "Slovakia", esp: "Eslovaquia", fra: "Slovaquie" },
  { hun: "Szlovénia", eng: "Slovenia", esp: "Eslovenia", fra: "Slovénie" },
  {
    hun: "Salamon-szigetek",
    eng: "Solomon Islands",
    esp: "Islas Salomón",
    fra: "Îles Salomon",
  },
  { hun: "Szomália", eng: "Somalia", esp: "Somalia", fra: "Somalie" },
  {
    hun: "Dél-Afrika",
    eng: "South Africa",
    esp: "Sudáfrica",
    fra: "Afrique du Sud",
  },
  {
    hun: "Déli-Georgia és Déli-Sandwich-szigetek",
    eng: "South Georgia and the South Sandwich Islands",
    esp: "Islas Georgias del Sur y Sandwich del Sur",
    fra: "Géorgie du Sud-et-les îles Sandwich du Sud",
  },
  { hun: "Spanyolország", eng: "Spain", esp: "España", fra: "Espagne" },
  { hun: "Sri Lanka", eng: "Sri Lanka", esp: "Sri Lanka", fra: "Sri Lanka" },
  { hun: "Szudán", eng: "Sudan", esp: "Sudán", fra: "Soudan" },
  { hun: "Suriname", eng: "Suriname", esp: "Surinam", fra: "Suriname" },
  {
    hun: "Spitzbergák és Jan Mayen",
    eng: "Svalbard and Jan Mayen",
    esp: "Svalbard y Jan Mayen",
    fra: "Svalbard et Jan Mayen",
  },
  {
    hun: "Szváziföld",
    eng: "Swaziland",
    esp: "Suazilandia",
    fra: "Swaziland",
  },
  { hun: "Svédország", eng: "Sweden", esp: "Suecia", fra: "Suède" },
  { hun: "Svájc", eng: "Switzerland", esp: "Suiza", fra: "Suisse" },
  {
    hun: "Szíriai Arab Köztársaság",
    eng: "Syrian Arab Republic",
    esp: "República Árabe Siria",
    fra: "République arabe syrienne",
  },
  {
    hun: "Kínai Köztársaság, Tajvan",
    eng: "Taiwan, Province of China",
    esp: "Taiwán, Provincia de China",
    fra: "Taïwan, Province de Chine",
  },
  {
    hun: "Tádzsikisztán",
    eng: "Tajikistan",
    esp: "Tayikistán",
    fra: "Tadjikistan",
  },
  {
    hun: "Tanzánia, Egyesült Köztársaság",
    eng: "Tanzania, United Republic of",
    esp: "Tanzania, República Unida de",
    fra: "Tanzanie, République-Unie de",
  },
  { hun: "Thaiföld", eng: "Thailand", esp: "Tailandia", fra: "Thaïlande" },
  {
    hun: "Kelet-Timor",
    eng: "Timor-Leste",
    esp: "Timor Oriental",
    fra: "Timor-Leste",
  },
  { hun: "Togo", eng: "Togo", esp: "Togo", fra: "Togo" },
  { hun: "Tokelau", eng: "Tokelau", esp: "Tokelau", fra: "Tokelau" },
  { hun: "Tonga", eng: "Tonga", esp: "Tonga", fra: "Tonga" },
  {
    hun: "Trinidad és Tobago",
    eng: "Trinidad and Tobago",
    esp: "Trinidad y Tobago",
    fra: "Trinité-et-Tobago",
  },
  { hun: "Tunézia", eng: "Tunisia", esp: "Túnez", fra: "Tunisie" },
  { hun: "Törökország", eng: "Turkey", esp: "Turquía", fra: "Turquie" },
  {
    hun: "Türkmenisztán",
    eng: "Turkmenistan",
    esp: "Turkmenistán",
    fra: "Turkménistan",
  },
  {
    hun: "Turks- és Caicos-szigetek",
    eng: "Turks and Caicos Islands",
    esp: "Islas Turks y Caicos",
    fra: "Îles Turks et Caicos",
  },
  { hun: "Tuvalu", eng: "Tuvalu", esp: "Tuvalu", fra: "Tuvalu" },
  { hun: "Uganda", eng: "Uganda", esp: "Uganda", fra: "Ouganda" },
  { hun: "Ukrajna", eng: "Ukraine", esp: "Ucrania", fra: "Ukraine" },
  {
    hun: "Egyesült Arab Emírségek",
    eng: "United Arab Emirates",
    esp: "Emiratos Árabes Unidos",
    fra: "Émirats arabes unis",
  },
  {
    hun: "Egyesült Királyság",
    eng: "United Kingdom",
    esp: "Reino Unido",
    fra: "Royaume-Uni",
  },
  {
    hun: "Egyesült Államok",
    eng: "United States",
    esp: "Estados Unidos",
    fra: "États-Unis",
  },
  {
    hun: "Egyesült Államok Külső Szigetei",
    eng: "United States Minor Outlying Islands",
    esp: "Islas Ultramarinas Menores de Estados Unidos",
    fra: "Îles mineures éloignées des États-Unis",
  },
  { hun: "Uruguay", eng: "Uruguay", esp: "Uruguay", fra: "Uruguay" },
  {
    hun: "Üzbegisztán",
    eng: "Uzbekistan",
    esp: "Uzbekistán",
    fra: "Ouzbékistan",
  },
  { hun: "Vanuatu", eng: "Vanuatu", esp: "Vanuatu", fra: "Vanuatu" },
  { hun: "Venezuela", eng: "Venezuela", esp: "Venezuela", fra: "Venezuela" },
  { hun: "Vietnám", eng: "Viet Nam", esp: "Vietnam", fra: "Vietnam" },
  {
    hun: "Brit Virgin-szigetek",
    eng: "Virgin Islands, British",
    esp: "Islas Vírgenes Británicas",
    fra: "Îles Vierges britanniques",
  },
  {
    hun: "Amerikai Virgin-szigetek",
    eng: "Virgin Islands, U.S.",
    esp: "Islas Vírgenes de los Estados Unidos",
    fra: "Îles Vierges américaines",
  },
  {
    hun: "Wallis és Futuna",
    eng: "Wallis and Futuna",
    esp: "Wallis y Futuna",
    fra: "Wallis-et-Futuna",
  },
  {
    hun: "Nyugat-Szahara",
    eng: "Western Sahara",
    esp: "Sahara Occidental",
    fra: "Sahara occidental",
  },
  { hun: "Jemen", eng: "Yemen", esp: "Yemen", fra: "Yémen" },
  { hun: "Zambia", eng: "Zambia", esp: "Zambia", fra: "Zambie" },
  { hun: "Zimbabwe", eng: "Zimbabwe", esp: "Zimbabue", fra: "Zimbabwe" },
];

export default countries;
