export const colors = {
  common: {
    red: "#ce5a4f",
    green: "#49be25",
    yellowdark: "#efa75c",
    yellowlight: "#eace9b",
    purple: "#6554af",
  },
  pink: {
    primary: "#ebe0d0",
    secondary: "#fefefe",
    text: "#2b2730",
    textlight: "#ffffff",
    title: "#4a3a3b",
    dark: "#df919f",
    light: "#fcdfda",
    glasslight: "#ec9ec0cc",
    glassdark: "#6554af90",
    logo: "#e45a84",
  },
  blue: {
    primary: "#d0dbeb",
    secondary: "#ecfbfd",
    text: "#2b2730",
    textlight: "#ffffff",
    title: "#4a3a3b",
    dark: "#919fdf",
    light: "#daf7fc",
    glasslight: "#9ec0eccc",
    glassdark: "#b2a9d790",
    logo: "#5a84e4",
  },
  green: {
    primary: "#dbebd0",
    secondary: "#ecfdf7",
    text: "#2b2730",
    textlight: "#ffffff",
    title: "#4a3a3b",
    dark: "#9fdf91",
    light: "#dafcdf",
    glasslight: "#c0ec9ecc",
    glassdark: "#54af6590",
    logo: "#69b648",
  },
  brown: {
    primary: "#dbc2a9",
    secondary: "#ecfbfd",
    text: "#2b2730",
    textlight: "#ffffff",
    title: "#4a3a3b",
    dark: "#df919f",
    light: "#fcdfda",
    glasslight: "#ec9ec0cc",
    glassdark: "#6554af90",
    logo: "#5a84e4",
  },
};
